"""
Phase 13: E2E Weaviate + Hamlet Tests
=======================================
Mirrors test_e2e_milvus_hamlet.py for the Weaviate backend.
Requires Weaviate running on localhost:8088 (Docker).

Run API-level tests:
    python -m pytest tests/phase13/test_e2e_weaviate_hamlet.py -v --tb=short

Start Weaviate via Docker:
    docker run -d -p 8088:8080 semitechnologies/weaviate:latest
"""
from __future__ import annotations

import socket
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(ROOT))

import pytest
from fastapi.testclient import TestClient

from api.main import app
from tests.phase13.conftest_shared_hamlet import (
    HamletE2ESuite,
    make_hamlet_pipeline_fixture,
    make_patched_client_fixture,
)

# ── Docker port check — skip entire module if Weaviate not reachable ──────────

DOCKER_PORT = 8088


def _port_open(port: int) -> bool:
    try:
        with socket.create_connection(("localhost", port), timeout=2):
            return True
    except OSError:
        return False


pytestmark = pytest.mark.skipif(
    not _port_open(DOCKER_PORT),
    reason=f"Weaviate not reachable (Docker not running on port {DOCKER_PORT})",
)

# ── Test configuration ────────────────────────────────────────────────────────

BACKEND = "weaviate"
COLLECTION = "e2e_hamlet_weaviate"
SEARCH_QUERY = "Touching this dreaded sight"
ALL_METHODS = {
    "enable_dense": True,
    "enable_bm25": True,
    "enable_graph": True,
    "enable_rerank": True,
    "enable_mmr": True,
    "enable_rewrite": False,
    "enable_multi_query": False,
    "enable_hyde": False,
    "enable_raptor": False,
    "enable_contextual_rerank": False,
}

_CLIENT = TestClient(app, raise_server_exceptions=False)

# ── Module-level fixtures (generated by factories) ────────────────────────────

hamlet_pipeline = make_hamlet_pipeline_fixture(BACKEND, COLLECTION)
patched_search_client = make_patched_client_fixture(BACKEND, _CLIENT)


# ── Shared hamlet_text fixture ────────────────────────────────────────────────

@pytest.fixture(scope="module")
def hamlet_text():
    """Load Hamlet text; skip if file not found."""
    p = ROOT / "data" / "shakespeare_hamlet.txt"
    if not p.exists():
        pytest.skip(f"Hamlet corpus not found at {p}")
    text = p.read_text(encoding="utf-8", errors="ignore")
    assert len(text) > 1000, "Hamlet file appears empty"
    return text


# ── Test classes (inherit shared test methods) ────────────────────────────────

class TestHealth(HamletE2ESuite.TestHealth):
    BACKEND = BACKEND
    COLLECTION = COLLECTION
    CLIENT = _CLIENT
    SEARCH_QUERY = SEARCH_QUERY
    ALL_METHODS = ALL_METHODS


class TestBackends(HamletE2ESuite.TestBackends):
    BACKEND = BACKEND
    COLLECTION = COLLECTION
    CLIENT = _CLIENT
    SEARCH_QUERY = SEARCH_QUERY
    ALL_METHODS = ALL_METHODS


class TestChunkPreview(HamletE2ESuite.TestChunkPreview):
    BACKEND = BACKEND
    COLLECTION = COLLECTION
    CLIENT = _CLIENT
    SEARCH_QUERY = SEARCH_QUERY
    ALL_METHODS = ALL_METHODS


class TestIngestion(HamletE2ESuite.TestIngestion):
    BACKEND = BACKEND
    COLLECTION = COLLECTION
    CLIENT = _CLIENT
    SEARCH_QUERY = SEARCH_QUERY
    ALL_METHODS = ALL_METHODS


class TestCollections(HamletE2ESuite.TestCollections):
    BACKEND = BACKEND
    COLLECTION = COLLECTION
    CLIENT = _CLIENT
    SEARCH_QUERY = SEARCH_QUERY
    ALL_METHODS = ALL_METHODS


class TestSearch(HamletE2ESuite.TestSearch):
    BACKEND = BACKEND
    COLLECTION = COLLECTION
    CLIENT = _CLIENT
    SEARCH_QUERY = SEARCH_QUERY
    ALL_METHODS = ALL_METHODS


class TestRRFFusion(HamletE2ESuite.TestRRFFusion):
    BACKEND = BACKEND
    COLLECTION = COLLECTION
    CLIENT = _CLIENT
    SEARCH_QUERY = SEARCH_QUERY
    ALL_METHODS = ALL_METHODS


class TestLLMTrace(HamletE2ESuite.TestLLMTrace):
    BACKEND = BACKEND
    COLLECTION = COLLECTION
    CLIENT = _CLIENT
    SEARCH_QUERY = SEARCH_QUERY
    ALL_METHODS = ALL_METHODS


class TestPromptManagement(HamletE2ESuite.TestPromptManagement):
    BACKEND = BACKEND
    COLLECTION = COLLECTION
    CLIENT = _CLIENT
    SEARCH_QUERY = SEARCH_QUERY
    ALL_METHODS = ALL_METHODS


class TestFeedback(HamletE2ESuite.TestFeedback):
    BACKEND = BACKEND
    COLLECTION = COLLECTION
    CLIENT = _CLIENT
    SEARCH_QUERY = SEARCH_QUERY
    ALL_METHODS = ALL_METHODS


class TestParallelRetrieval(HamletE2ESuite.TestParallelRetrieval):
    BACKEND = BACKEND
    COLLECTION = COLLECTION
    CLIENT = _CLIENT
    SEARCH_QUERY = SEARCH_QUERY
    ALL_METHODS = ALL_METHODS


class TestCrossEncoderCache(HamletE2ESuite.TestCrossEncoderCache):
    BACKEND = BACKEND
    COLLECTION = COLLECTION
    CLIENT = _CLIENT


class TestPipelineCache(HamletE2ESuite.TestPipelineCache):
    BACKEND = BACKEND
    COLLECTION = COLLECTION
    CLIENT = _CLIENT


class TestGraphSnapshotRestore(HamletE2ESuite.TestGraphSnapshotRestore):
    BACKEND = BACKEND
    COLLECTION = COLLECTION
    CLIENT = _CLIENT
    # Use the per-backend E2E collection for snapshot checks
    SNAPSHOT_COLLECTION = COLLECTION


class TestBrowserSmoke(HamletE2ESuite.TestBrowserSmoke):
    BACKEND = BACKEND
    COLLECTION = COLLECTION
    CLIENT = _CLIENT
    SEARCH_QUERY = SEARCH_QUERY
